name: live_code
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  get_storage: ^2.1.1
  dart_ping_ios: ^4.0.2
  http: ^1.2.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  flutter_svg: ^2.0.10+1
  marquee: ^2.2.3
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "resources/live.png"
  image_path_android: "resources/live.png"
  web:
    generate: true
    image_path: "resources/live.png"
  windows:
    generate: true
    image_path: "resources/live.png"
  macos:
    generate: true
    image_path: "resources/live.png"

dependency_overrides:
  fading_edge_scrollview: ^4.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/illustrations/
    - assets/fonts/
  fonts:
    - family: PlusJakartaSansBold
      fonts:
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Bold.ttf
          style: normal
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-BoldItalic.ttf
          style: italic
    - family: PlusJakartaSansSemiBold
      fonts:
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-SemiBold.ttf
          style: normal
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-SemiBoldItalic.ttf
          style: italic
    - family: PlusJakartaSansMedium
      fonts:
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Medium.ttf
          style: normal
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-MediumItalic.ttf
          style: italic
    - family: PlusJakartaSansRegular
      fonts:
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Regular.ttf
          style: normal
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Italic.ttf
          style: italic